dist: focal
language: node_js
node_js:
    - "node"
sudo: false
install:
    - npm install -g enactjs/cli#develop
    - npm install
    - cd ./packages/theme/template
    - npm install
script:
    - npm run lint
