dist: focal
language: node_js
node_js:
    - node
sudo: false
install:
    - git clone --branch=develop --depth 1 https://github.com/enactjs/cli ../cli
    - pushd ../cli
    - npm install
    - npm link
    - popd
    - npm install -g eslint
    - npm install
    - cd ./packages/theme/template
    - npm install
script:
    - echo -e "\x1b\x5b35;1m*** Starting lint and tests from theme template...\x1b\x5b0m"
    - npm run lint -- --report-unused-disable-directives --max-warnings 0
    - npm run test
    - echo -e "\x1b\x5b35;1m*** Tests complete\x1b\x5b0m"
    - cd ../../..
    - echo -e "\x1b\x5b35;1m*** Starting eslint...\x1b\x5b0m"
    - npm run lint -- --report-unused-disable-directives --max-warnings 0
    - echo -e "\x1b\x5b35;1m*** eslint complete\x1b\x5b0m"
