dist: focal
language: node_js
node_js:
    - "node"
sudo: false
install:
    - npm install -g enactjs/cli#develop
    - npm install --save-dev eslint-config-enact-proxy
    - cd ./packages/theme/template
    - npm install
script:
    - echo -e "\x1b\x5b35;1m*** Starting tests from theme template...\x1b\x5b0m"
    - npm run test
    - echo -e "\x1b\x5b35;1m*** Tests complete\x1b\x5b0m"
    - echo -e "\x1b\x5b35;1m*** Starting eslint...\x1b\x5b0m"
    - npm run lint
    - cd ../../..
    - npm uninstall -g enactjs/cli
    - npm run lint
    - echo -e "\x1b\x5b35;1m*** eslint complete\x1b\x5b0m"
